source 'https://rubygems.org'
ruby "2.0.0"

gem 'sinatra', '~> 1.4.5'
gem 'thin', '~> 1.6.3'
gem 'omniauth', '~> 1.2.2'
gem 'couchrest_model', '~> 2.0.3'
gem 'rack-cors', '~> 0.2.9'
gem 'rspec', '3.1.0'
gem 'activesupport', '4.1.8'
gem 'octokit', '~> 3.0'
gem 'pony', '~> 1.11'
gem 'rack-throttle', '~> 0.4'
gem 'newrelic_rpm'
gem 'faye-websocket'
